#!/usr/bin/env python3
"""
Minimal runnable evaluator for the revised Beta-tensor trust derivation.
Implements: trust anchors, chain-height stratification, null-for-unmeasured,
strength-weighted parent aggregation, recursive Integrity provenance, and
strictly-below dependency weighting.

This script is intentionally small and self-contained so the test vectors can be
regenerated by running it, addressing the reproducibility finding in
review-claude-code-2026-07-24-of-kimi-proposal.md.
"""
from __future__ import annotations
from dataclasses import dataclass
from math import sqrt
from typing import Dict, List, Optional, Tuple


@dataclass(frozen=True)
class Obs:
    subject: str          # entity being scored
    dimension: str        # leaf dimension (e.g. web4:BoundaryResponse)
    mrh: str              # MRH context
    c: float              # confidence from evidence_rules
    adjudicator: str      # source grain
    height: int = 0       # chain height for stratification
    # Each dependency is (subject, dimension) under the same MRH as this obs.
    depends_on: Tuple[Tuple[str, str], ...] = ()


@dataclass
class Score:
    mu: float
    sigma: float
    strength: float


DEFAULT_PARAMS = {
    "prior_alpha": 1.0,
    "prior_beta": 1.0,
    "unmeasured_if_total_weight_below": 0.01,
    "provenance_unmeasured_weight": 0.0,
    "dependency_discount_per_hop": 0.5,
    "decay_halflife_days": 90,
    "max_weight_per_source_per_halflife": None,
    # Which statistic of the adjudicator's Integrity is used for provenance weight.
    # "mean" -> mu; "lower_bound" -> max(0, mu - sigma).
    "provenance_weight_statistic": "mean",
}


DIMENSIONS = {
    "web4:Validity": ["web4:BoundaryResponse", "web4:CorrectionAcceptance", "web4:EscalationProportionality"],
    "web4:Reliability": ["web4:TaskCompletion", "web4:Compliance"],
    "web4:Integrity": ["web4:AdjudicationQuality"],
}


def provenance_statistic(score: Score, statistic: str) -> float:
    if statistic == "lower_bound":
        return max(0.0, score.mu - score.sigma)
    return score.mu


def beta_update(params: Dict, observations: List[Obs], weights: List[float]) -> Optional[Score]:
    """Compute Beta score from observations and their effective weights."""
    assert len(observations) == len(weights)
    scw = sum(obs.c * w for obs, w in zip(observations, weights))
    s1cw = sum((1 - obs.c) * w for obs, w in zip(observations, weights))
    total_w = sum(weights)

    if total_w < params["unmeasured_if_total_weight_below"]:
        return None

    a = params["prior_alpha"] + scw
    b = params["prior_beta"] + s1cw
    mu = a / (a + b)
    sigma = sqrt(a * b / ((a + b) ** 2 * (a + b + 1)))
    strength = a + b - params["prior_alpha"] - params["prior_beta"]
    return Score(mu, sigma, strength)


def evaluate_dimension(
    params: Dict,
    subject: str,
    dimension: str,
    mrh: str,
    observations: List[Obs],
    anchors: List[str],
    measured_adjudicators: List[str],
    cache: Dict[Tuple[str, str, int], Optional[Score]],
    height: int,
) -> Optional[Score]:
    """Evaluate subject*dimension under mrh using evidence strictly below height.

    Returns the score at upper-bound ``height`` (exclusive).  The final,
    all-evidence score is obtained by calling with height = max_height + 1.
    """
    key = (subject, dimension, height)
    if key in cache:
        return cache[key]

    # Evidence eligible for this upper bound.
    eligible = [o for o in observations if o.height < height]

    children = DIMENSIONS.get(dimension)
    if children:
        measured: List[Score] = []
        for child in children:
            s = evaluate_dimension(params, subject, child, mrh, eligible, anchors, measured_adjudicators, cache, height)
            if s is not None:
                measured.append(s)
        if not measured:
            result: Optional[Score] = None
        else:
            total_strength = sum(s.strength for s in measured)
            mu = sum(s.mu * s.strength for s in measured) / total_strength
            sigma = sqrt(
                sum((s.strength / total_strength) ** 2 * s.sigma ** 2 for s in measured)
            )
            result = Score(mu, sigma, total_strength)
        cache[key] = result
        return result

    # Leaf dimension.
    leaf_obs = [
        o for o in eligible
        if o.subject == subject and o.dimension == dimension and o.mrh == mrh
    ]
    weights = []
    for obs in leaf_obs:
        # Provenance weight: adjudicator's Integrity over evidence strictly below obs.height.
        if obs.adjudicator in anchors or obs.adjudicator in measured_adjudicators:
            wp = 1.0
        else:
            adj_score = evaluate_dimension(
                params, obs.adjudicator, "web4:Integrity", obs.mrh,
                eligible, anchors, measured_adjudicators, cache, obs.height,
            )
            if adj_score is None:
                wp = params["provenance_unmeasured_weight"]
            else:
                wp = provenance_statistic(adj_score, params["provenance_weight_statistic"])

        # Dependency weight: product over deps, each taken strictly below obs.height.
        wd = 1.0
        for dep_subject, dep_dimension in obs.depends_on:
            dep_score = evaluate_dimension(
                params, dep_subject, dep_dimension, obs.mrh,
                eligible, anchors, measured_adjudicators, cache, obs.height,
            )
            if dep_score is None:
                wd = 0.0
                break
            wd *= dep_score.mu * params["dependency_discount_per_hop"]

        wt = 1.0  # age ≈ 0 in the vectors
        weights.append(max(0.0, min(1.0, wp * wd * wt)))

    result = beta_update(params, leaf_obs, weights)
    cache[key] = result
    return result


def fmt(s: Optional[Score]) -> str:
    if s is None:
        return "null"
    return f"{s.mu:.3f} ± {s.sigma:.3f}, strength {s.strength:.1f}"


def report_height(observations: List[Obs]) -> int:
    if not observations:
        return 1
    return max(o.height for o in observations) + 1


def main():
    params = DEFAULT_PARAMS.copy()

    # ------------------------------------------------------------------ V1
    subject = "kimi-code"
    v1_obs = []
    for _ in range(6):
        v1_obs.append(Obs(subject, "web4:BoundaryResponse", "interactive-dev", 1.0, "measured-adj", height=100))
    for _ in range(12):
        v1_obs.append(Obs(subject, "web4:BoundaryResponse", "interactive-dev", 0.7, "measured-adj", height=100))

    h1 = report_height(v1_obs)
    print("V1 (kimi-code / interactive-dev day one)")
    print(f"  Validity, measured_adj=[]     -> {fmt(evaluate_dimension(params, subject, 'web4:Validity', 'interactive-dev', v1_obs, [], [], {}, h1))}")
    print(f"  Validity, measured_adj=[m]    -> {fmt(evaluate_dimension(params, subject, 'web4:Validity', 'interactive-dev', v1_obs, [], ['measured-adj'], {}, h1))}")
    print()

    # ------------------------------------------------------------------ V2
    print("V2 (member-bucket: 14 self-reports)")
    print("  -> null (self-reports match no evidence rule)")
    print()

    # ------------------------------------------------------------------ V3
    v3_obs = []
    for _ in range(5):
        v3_obs.append(Obs(subject, "web4:BoundaryResponse", "interactive-dev", 1.0, "adjudicator-X", height=100))

    h3 = report_height(v3_obs)
    print("V3 (adjudicator capture)")
    print(f"  harsh default (unmeasured weight 0.0) -> {fmt(evaluate_dimension(params, subject, 'web4:Validity', 'interactive-dev', v3_obs, [], [], {}, h3))}")
    eps_params = params.copy()
    eps_params["provenance_unmeasured_weight"] = 0.1
    print(f"  epsilon variant (weight 0.1)          -> {fmt(evaluate_dimension(eps_params, subject, 'web4:Validity', 'interactive-dev', v3_obs, [], [], {}, h3))}")
    print()

    # ------------------------------------------------------------------ V4
    v4_obs = []
    for _ in range(3):
        v4_obs.append(Obs("member-M", "web4:BoundaryResponse", "interactive-dev", 1.0, "operator", height=100))

    h4 = report_height(v4_obs)
    print("V4 (genesis bootstrap)")
    print(f"  with anchors=[operator]    -> {fmt(evaluate_dimension(params, 'member-M', 'web4:Validity', 'interactive-dev', v4_obs, ['operator'], [], {}, h4))}")
    print(f"  with anchors=[]            -> {fmt(evaluate_dimension(params, 'member-M', 'web4:Validity', 'interactive-dev', v4_obs, [], [], {}, h4))}")
    print()

    # ------------------------------------------------------------------ V5
    v5_obs = []
    for _ in range(3):
        v5_obs.append(Obs("member-M", "web4:BoundaryResponse", "interactive-dev", 1.0, "measured-adj", height=100))
    v5_obs.append(Obs("member-M", "web4:CorrectionAcceptance", "interactive-dev", 1.0, "measured-adj", height=100))
    for _ in range(2):
        v5_obs.append(Obs("member-M", "web4:CorrectionAcceptance", "interactive-dev", 0.7, "measured-adj", height=100))

    h5 = report_height(v5_obs)
    cache: Dict[Tuple[str, str, int], Optional[Score]] = {}
    print("V5 (fractal aggregation)")
    print(f"  web4:BoundaryResponse          -> {fmt(evaluate_dimension(params, 'member-M', 'web4:BoundaryResponse', 'interactive-dev', v5_obs, [], ['measured-adj'], cache, h5))}")
    print(f"  web4:CorrectionAcceptance      -> {fmt(evaluate_dimension(params, 'member-M', 'web4:CorrectionAcceptance', 'interactive-dev', v5_obs, [], ['measured-adj'], cache, h5))}")
    print(f"  web4:EscalationProportionality -> {fmt(evaluate_dimension(params, 'member-M', 'web4:EscalationProportionality', 'interactive-dev', v5_obs, [], ['measured-adj'], cache, h5))}")
    print(f"  parent web4:Validity           -> {fmt(evaluate_dimension(params, 'member-M', 'web4:Validity', 'interactive-dev', v5_obs, [], ['measured-adj'], cache, h5))}")
    print()

    # ------------------------------------------------------------------ V6a
    # Anchor O -> adjudicator A -> member M, across strata.
    v6a_obs = []
    for _ in range(4):
        v6a_obs.append(Obs("adjudicator-A", "web4:AdjudicationQuality", "interactive-dev", 1.0, "operator", height=10))
    for _ in range(5):
        v6a_obs.append(Obs("member-M", "web4:BoundaryResponse", "interactive-dev", 1.0, "adjudicator-A", height=20))

    h6a = report_height(v6a_obs)
    print("V6a (computed provenance across strata)")
    print(f"  adjudicator-A web4:Integrity   -> {fmt(evaluate_dimension(params, 'adjudicator-A', 'web4:Integrity', 'interactive-dev', v6a_obs, ['operator'], [], {}, h6a))}")
    print(f"  member-M web4:BoundaryResponse -> {fmt(evaluate_dimension(params, 'member-M', 'web4:BoundaryResponse', 'interactive-dev', v6a_obs, ['operator'], [], {}, h6a))}")
    # Control: no anchor -> A unmeasured -> M null.
    print(f"  control (no anchor)            -> {fmt(evaluate_dimension(params, 'member-M', 'web4:BoundaryResponse', 'interactive-dev', v6a_obs, [], [], {}, h6a))}")
    print()

    # ------------------------------------------------------------------ V6b
    # Dependency discount vector: product semantics, discount 0.5.
    # Subject S scores 0.640 on BoundaryResponse; M depends on S.
    v6b_obs = [
        Obs("subject-S", "web4:BoundaryResponse", "interactive-dev", 0.92, "measured-adj", height=10),
        Obs("member-M", "web4:BoundaryResponse", "interactive-dev", 1.0, "measured-adj", height=20, depends_on=(("subject-S", "web4:BoundaryResponse"),)),
    ]

    h6b = report_height(v6b_obs)
    print("V6b (dependency discount, product semantics)")
    print(f"  subject-S web4:BoundaryResponse -> {fmt(evaluate_dimension(params, 'subject-S', 'web4:BoundaryResponse', 'interactive-dev', v6b_obs, [], ['measured-adj'], {}, h6b))}")
    print(f"  member-M web4:BoundaryResponse  -> {fmt(evaluate_dimension(params, 'member-M', 'web4:BoundaryResponse', 'interactive-dev', v6b_obs, [], ['measured-adj'], {}, h6b))}")
    print()

    # ------------------------------------------------------------------ V4b
    # Anchor drift visibility: O anchors M, but O's derived Integrity is low.
    v4b_obs = []
    for _ in range(3):
        v4b_obs.append(Obs("member-M", "web4:BoundaryResponse", "interactive-dev", 1.0, "operator", height=10))
    # Another measured adjudicator overturns one of O's adjudication acts.
    v4b_obs.append(Obs("operator", "web4:AdjudicationQuality", "interactive-dev", 0.0, "measured-adj", height=20))

    h4b = report_height(v4b_obs)
    print("V4b (anchor drift visibility)")
    print(f"  member-M web4:BoundaryResponse (anchored by operator) -> {fmt(evaluate_dimension(params, 'member-M', 'web4:BoundaryResponse', 'interactive-dev', v4b_obs, ['operator'], ['measured-adj'], {}, h4b))}")
    print(f"  operator derived web4:Integrity                       -> {fmt(evaluate_dimension(params, 'operator', 'web4:Integrity', 'interactive-dev', v4b_obs, ['operator'], ['measured-adj'], {}, h4b))}")


if __name__ == "__main__":
    main()
